/// FFI bridge generation for incremental migration.
///
/// When migrating functions one at a time, we need:
/// - Rust `extern "C"` blocks to call unmigrated C functions
/// - C header declarations for Rust functions callable from C
/// - A mixed module combining migrated Rust and unmigrated C stubs
use crate::ast::CFunction;

/// Generate Rust `extern "C"` block for unmigrated C functions.
///
/// These declarations allow migrated Rust code to call C functions
/// that haven't been migrated yet.
pub fn generate_rust_extern_block(c_functions: &[CFunction]) -> String {
    if c_functions.is_empty() {
        return String::new();
    }

    let mut block = String::from("extern \"C\" {\n");
    for func in c_functions {
        let rust_sig = c_sig_to_rust_extern(&func.name, &func.return_type, &func.body);
        block.push_str(&format!("    {rust_sig}\n"));
    }
    block.push_str("}\n");
    block
}

/// Generate a C header for migrated Rust functions.
///
/// These declarations allow unmigrated C code to call Rust functions
/// via `#[no_mangle] extern "C"`.
pub fn generate_c_header_for_rust(migrated_functions: &[(String, String)]) -> String {
    let mut header = String::from("/* Auto-generated by Noricum for incremental migration */\n");
    header.push_str("#ifndef NORICUM_FFI_H\n#define NORICUM_FFI_H\n\n");

    for (name, rust_sig) in migrated_functions {
        let c_decl = rust_sig_to_c_decl(name, rust_sig);
        header.push_str(&format!("{c_decl};\n"));
    }

    header.push_str("\n#endif /* NORICUM_FFI_H */\n");
    header
}

/// Generate a mixed Rust module with migrated functions and extern stubs.
pub fn generate_mixed_rust_module(
    migrated: &[(String, String)],
    unmigrated: &[CFunction],
) -> String {
    let mut module = String::new();

    // Add extern block for unmigrated C functions
    if !unmigrated.is_empty() {
        module.push_str(&generate_rust_extern_block(unmigrated));
        module.push('\n');
    }

    // Add migrated Rust functions
    for (_name, rust_code) in migrated {
        module.push_str(rust_code);
        module.push_str("\n\n");
    }

    module
}

/// Convert a C function signature to a Rust extern "C" declaration.
///
/// This is a best-effort conversion; complex types may need manual adjustment.
fn c_sig_to_rust_extern(name: &str, return_type: &str, _body: &str) -> String {
    let rust_return = c_type_to_rust(return_type);
    if rust_return.is_empty() || rust_return == "()" {
        format!("fn {name}();")
    } else {
        format!("fn {name}() -> {rust_return};")
    }
}

/// Convert a Rust function signature to a C declaration.
fn rust_sig_to_c_decl(name: &str, rust_sig: &str) -> String {
    // Extract return type from Rust signature
    if rust_sig.contains("-> i32") {
        format!("int {name}()")
    } else if rust_sig.contains("-> f64") {
        format!("double {name}()")
    } else {
        format!("void {name}()")
    }
}

/// Convert a C type string to its Rust equivalent.
fn c_type_to_rust(c_type: &str) -> String {
    let trimmed = c_type.trim();
    match trimmed {
        "void" => "()".to_string(),
        "int" => "i32".to_string(),
        "unsigned int" | "unsigned" => "u32".to_string(),
        "long" => "i64".to_string(),
        "unsigned long" => "u64".to_string(),
        "char" => "i8".to_string(),
        "unsigned char" => "u8".to_string(),
        "float" => "f32".to_string(),
        "double" => "f64".to_string(),
        "size_t" => "usize".to_string(),
        "bool" | "_Bool" => "bool".to_string(),
        t if t.contains('*') => "*mut std::ffi::c_void".to_string(),
        _ => "std::ffi::c_int".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_extern_block() {
        let funcs = vec![
            CFunction {
                name: "add".to_string(),
                return_type: "int".to_string(),
                body: String::new(),
                start_byte: 0,
                end_byte: 0,
            },
            CFunction {
                name: "greet".to_string(),
                return_type: "void".to_string(),
                body: String::new(),
                start_byte: 0,
                end_byte: 0,
            },
        ];
        let block = generate_rust_extern_block(&funcs);
        assert!(block.contains("extern \"C\""));
        assert!(block.contains("fn add() -> i32"));
        assert!(block.contains("fn greet()"));
    }

    #[test]
    fn test_generate_extern_block_empty() {
        let block = generate_rust_extern_block(&[]);
        assert!(block.is_empty());
    }

    #[test]
    fn test_generate_c_header() {
        let migrated = vec![(
            "add".to_string(),
            "fn add(a: i32, b: i32) -> i32".to_string(),
        )];
        let header = generate_c_header_for_rust(&migrated);
        assert!(header.contains("NORICUM_FFI_H"));
        assert!(header.contains("int add()"));
    }

    #[test]
    fn test_c_type_to_rust() {
        assert_eq!(c_type_to_rust("int"), "i32");
        assert_eq!(c_type_to_rust("void"), "()");
        assert_eq!(c_type_to_rust("double"), "f64");
        assert_eq!(c_type_to_rust("char *"), "*mut std::ffi::c_void");
        assert_eq!(c_type_to_rust("size_t"), "usize");
    }

    #[test]
    fn test_mixed_module() {
        let migrated = vec![(
            "add".to_string(),
            "pub fn add(a: i32, b: i32) -> i32 { a + b }".to_string(),
        )];
        let unmigrated = vec![CFunction {
            name: "helper".to_string(),
            return_type: "int".to_string(),
            body: String::new(),
            start_byte: 0,
            end_byte: 0,
        }];
        let module = generate_mixed_rust_module(&migrated, &unmigrated);
        assert!(module.contains("extern \"C\""));
        assert!(module.contains("fn helper"));
        assert!(module.contains("pub fn add"));
    }
}
