[workspace]

[package]
name = "noricum-spike-miniz"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "spike"
path = "src/lib.rs"

[build-dependencies]
cc = "1"

[dependencies]
flate2 = "1"
crc32fast = "1"

[dev-dependencies]
zip = { version = "2", default-features = false, features = ["deflate-flate2", "flate2", "aes-crypto", "time"] }
