/* miniz_core_combined.c — Standalone miniz core (checksums + DEFLATE + INFLATE)
 * Combined from miniz 3.1.0 for noricum diff testing.
 * NO ZIP, NO STDIO — pure compression/decompression only.
 *
 * Copyright 2013-2014 RAD Game Tools and Valve Software
 * Copyright 2010-2014 Rich Geldreich and Tenacious Software LLC
 * Released under the Unlicense (public domain).
 *
 * Compile: gcc -std=gnu11 -Wall -Wno-unused-function -o test miniz_core_combined.c
 */

/* Disable features we don't need */
#define MINIZ_NO_ARCHIVE_APIS
#define MINIZ_NO_ARCHIVE_WRITING_APIS
#define MINIZ_NO_STDIO
#define MINIZ_NO_TIME
#define MINIZ_NO_ZLIB_COMPATIBLE_NAMES

/* miniz_export.h is normally generated by CMake; define MINIZ_EXPORT as empty */
#define MINIZ_EXPORT

/* Include the miniz headers (they are in the same directory) */
#include "miniz.h"

/* Include the implementation files */
#include "miniz.c"
#include "miniz_tinfl.c"
#include "miniz_tdef.c"

/* ==================== Test Harness ==================== */

#include <stdio.h>

static int test_count = 0;
static int fail_count = 0;

static void check(int cond, const char *name) {
    test_count++;
    if (cond) {
        printf("ok %d - %s\n", test_count, name);
    } else {
        fail_count++;
        printf("not ok %d - %s\n", test_count, name);
    }
}

/* --- Checksum tests --- */
static void test_checksums(void) {
    printf("# Checksums\n");

    /* Adler-32 */
    const unsigned char hello[] = "Hello, World!";
    mz_ulong a = mz_adler32(MZ_ADLER32_INIT, hello, 13);
    check(a == 530449514, "adler32_hello");
    printf("# adler32_hello=%lu\n", a);

    mz_ulong a_empty = mz_adler32(MZ_ADLER32_INIT, (const unsigned char *)"", 0);
    check(a_empty == 1, "adler32_empty");

    mz_ulong a_null = mz_adler32(0, NULL, 0);
    check(a_null == 1, "adler32_null");

    /* Incremental adler32 */
    mz_ulong a_inc = mz_adler32(MZ_ADLER32_INIT, hello, 5);
    a_inc = mz_adler32(a_inc, hello + 5, 8);
    check(a_inc == a, "adler32_incremental");

    /* CRC-32 */
    mz_ulong c = mz_crc32(MZ_CRC32_INIT, hello, 13);
    check(c == 3964322768UL, "crc32_hello");
    printf("# crc32_hello=%lu\n", c);

    mz_ulong c_empty = mz_crc32(MZ_CRC32_INIT, (const unsigned char *)"", 0);
    check(c_empty == 0, "crc32_empty");

    mz_ulong c_null = mz_crc32(0, NULL, 0);
    check(c_null == 0, "crc32_null");

    /* Incremental crc32 */
    mz_ulong c_inc = mz_crc32(MZ_CRC32_INIT, hello, 5);
    c_inc = mz_crc32(c_inc, hello + 5, 8);
    check(c_inc == c, "crc32_incremental");
}

/* --- One-shot compress/uncompress round-trip --- */
static void test_oneshot_roundtrip(void) {
    printf("# One-shot compress/uncompress\n");

    const char *src = "The quick brown fox jumps over the lazy dog. "
                      "Pack my box with five dozen liquor jugs. "
                      "How vexingly quick daft zebras jump!";
    size_t src_len = strlen(src);

    /* Compress */
    mz_ulong comp_len = mz_compressBound(src_len);
    unsigned char *comp_buf = (unsigned char *)malloc(comp_len);
    check(comp_buf != NULL, "compress_alloc");

    int status = mz_compress(comp_buf, &comp_len, (const unsigned char *)src, src_len);
    check(status == MZ_OK, "compress_ok");
    check(comp_len > 0 && comp_len < src_len, "compressed_smaller");
    printf("# compressed: %lu -> %lu bytes\n", (unsigned long)src_len, (unsigned long)comp_len);

    /* Decompress */
    mz_ulong decomp_len = src_len;
    unsigned char *decomp_buf = (unsigned char *)malloc(decomp_len + 1);
    check(decomp_buf != NULL, "decompress_alloc");

    status = mz_uncompress(decomp_buf, &decomp_len, comp_buf, comp_len);
    check(status == MZ_OK, "uncompress_ok");
    check(decomp_len == src_len, "decompress_size_match");
    check(memcmp(decomp_buf, src, src_len) == 0, "decompress_data_match");

    free(comp_buf);
    free(decomp_buf);
}

/* --- Compress with different levels --- */
static void test_compression_levels(void) {
    printf("# Compression levels\n");

    /* Create repetitive data that compresses well */
    size_t src_len = 4096;
    unsigned char *src = (unsigned char *)malloc(src_len);
    for (size_t i = 0; i < src_len; i++)
        src[i] = (unsigned char)(i % 26 + 'A');

    int levels[] = { MZ_NO_COMPRESSION, MZ_BEST_SPEED, MZ_DEFAULT_COMPRESSION, MZ_BEST_COMPRESSION };
    const char *level_names[] = { "no_compression", "best_speed", "default", "best_compression" };

    for (int li = 0; li < 4; li++) {
        int level = levels[li];
        mz_ulong comp_len = mz_compressBound(src_len);
        unsigned char *comp = (unsigned char *)malloc(comp_len);

        int status = mz_compress2(comp, &comp_len, src, src_len, level);
        check(status == MZ_OK, level_names[li]);
        printf("# level_%s: %lu -> %lu bytes\n", level_names[li], (unsigned long)src_len, (unsigned long)comp_len);

        /* Verify round-trip */
        mz_ulong decomp_len = src_len;
        unsigned char *decomp = (unsigned char *)malloc(decomp_len);
        status = mz_uncompress(decomp, &decomp_len, comp, comp_len);
        char name[64];
        snprintf(name, sizeof(name), "%s_roundtrip", level_names[li]);
        check(status == MZ_OK && decomp_len == src_len && memcmp(decomp, src, src_len) == 0, name);

        free(comp);
        free(decomp);
    }

    free(src);
}

/* --- Streaming compress/decompress --- */
static void test_streaming(void) {
    printf("# Streaming deflate/inflate\n");

    /* Create test data */
    size_t src_len = 8192;
    unsigned char *src = (unsigned char *)malloc(src_len);
    for (size_t i = 0; i < src_len; i++)
        src[i] = (unsigned char)((i * 7 + 13) % 256);

    /* --- Streaming deflate --- */
    mz_stream def_stream;
    memset(&def_stream, 0, sizeof(def_stream));
    int status = mz_deflateInit(&def_stream, MZ_DEFAULT_COMPRESSION);
    check(status == MZ_OK, "deflateInit");

    mz_ulong comp_bound = mz_deflateBound(&def_stream, src_len);
    unsigned char *comp = (unsigned char *)malloc(comp_bound);

    /* Feed data in chunks */
    size_t chunk_size = 1000;
    size_t offset = 0;
    def_stream.next_out = comp;
    def_stream.avail_out = (unsigned int)comp_bound;

    while (offset < src_len) {
        size_t remaining = src_len - offset;
        size_t this_chunk = remaining < chunk_size ? remaining : chunk_size;
        def_stream.next_in = src + offset;
        def_stream.avail_in = (unsigned int)this_chunk;
        offset += this_chunk;

        int flush = (offset >= src_len) ? MZ_FINISH : MZ_NO_FLUSH;
        status = mz_deflate(&def_stream, flush);
        if (flush == MZ_FINISH) {
            check(status == MZ_STREAM_END, "deflate_finish");
        } else {
            check(status == MZ_OK, "deflate_chunk");
        }
    }

    mz_ulong comp_len = def_stream.total_out;
    printf("# streaming_deflate: %lu -> %lu bytes\n", (unsigned long)src_len, (unsigned long)comp_len);
    check(def_stream.total_in == src_len, "deflate_total_in");

    status = mz_deflateEnd(&def_stream);
    check(status == MZ_OK, "deflateEnd");

    /* --- Streaming inflate --- */
    mz_stream inf_stream;
    memset(&inf_stream, 0, sizeof(inf_stream));
    status = mz_inflateInit(&inf_stream);
    check(status == MZ_OK, "inflateInit");

    unsigned char *decomp = (unsigned char *)malloc(src_len);
    inf_stream.next_in = comp;
    inf_stream.avail_in = (unsigned int)comp_len;
    inf_stream.next_out = decomp;
    inf_stream.avail_out = (unsigned int)src_len;

    status = mz_inflate(&inf_stream, MZ_FINISH);
    check(status == MZ_STREAM_END, "inflate_finish");
    check(inf_stream.total_out == src_len, "inflate_total_out");
    check(memcmp(decomp, src, src_len) == 0, "inflate_data_match");

    /* Adler32 should match */
    mz_ulong src_adler = mz_adler32(MZ_ADLER32_INIT, src, src_len);
    check(inf_stream.adler == src_adler, "inflate_adler32_match");

    status = mz_inflateEnd(&inf_stream);
    check(status == MZ_OK, "inflateEnd");

    free(src);
    free(comp);
    free(decomp);
}

/* --- Low-level tdefl/tinfl API --- */
static void test_lowlevel(void) {
    printf("# Low-level tdefl/tinfl\n");

    const char *src = "AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCC"
                      "AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCC";
    size_t src_len = strlen(src);

    /* Compress with tdefl_compress_mem_to_heap */
    size_t comp_len = 0;
    int flags = tdefl_create_comp_flags_from_zip_params(MZ_DEFAULT_COMPRESSION, -MZ_DEFAULT_WINDOW_BITS, MZ_DEFAULT_STRATEGY);
    void *comp = tdefl_compress_mem_to_heap(src, src_len, &comp_len, flags);
    check(comp != NULL, "tdefl_compress_to_heap");
    check(comp_len > 0 && comp_len < src_len, "tdefl_compressed_smaller");
    printf("# tdefl: %lu -> %lu bytes\n", (unsigned long)src_len, (unsigned long)comp_len);

    /* Decompress with tinfl_decompress_mem_to_mem */
    unsigned char decomp[256];
    size_t decomp_len = tinfl_decompress_mem_to_mem(decomp, sizeof(decomp), comp, comp_len, 0);
    check(decomp_len == src_len, "tinfl_decompress_size");
    check(memcmp(decomp, src, src_len) == 0, "tinfl_decompress_match");

    /* Decompress with tinfl_decompress_mem_to_heap */
    size_t heap_len = 0;
    void *heap_decomp = tinfl_decompress_mem_to_heap(comp, comp_len, &heap_len, 0);
    check(heap_decomp != NULL, "tinfl_to_heap_alloc");
    check(heap_len == src_len, "tinfl_to_heap_size");
    check(memcmp(heap_decomp, src, src_len) == 0, "tinfl_to_heap_match");

    mz_free(heap_decomp);
    mz_free(comp);
}

/* --- Edge cases --- */
static void test_edge_cases(void) {
    printf("# Edge cases\n");

    /* Empty data compression */
    unsigned char comp[128];
    mz_ulong comp_len = sizeof(comp);
    int status = mz_compress(comp, &comp_len, (const unsigned char *)"", 0);
    check(status == MZ_OK, "compress_empty");
    printf("# empty_compressed_size=%lu\n", (unsigned long)comp_len);

    /* Decompress empty */
    unsigned char decomp[128];
    mz_ulong decomp_len = sizeof(decomp);
    status = mz_uncompress(decomp, &decomp_len, comp, comp_len);
    check(status == MZ_OK, "uncompress_empty");
    check(decomp_len == 0, "uncompress_empty_size");

    /* Version string */
    const char *ver = mz_version();
    check(ver != NULL && strlen(ver) > 0, "version_string");
    printf("# version=%s\n", ver);

    /* Error string */
    const char *err = mz_error(MZ_OK);
    check(err != NULL, "error_string_ok");
    const char *err_data = mz_error(MZ_DATA_ERROR);
    check(err_data != NULL && strcmp(err_data, "data error") == 0, "error_string_data");

    /* Compress bound */
    mz_ulong bound = mz_compressBound(1000);
    check(bound > 1000, "compress_bound");

    /* Single byte compression round-trip */
    unsigned char one_byte = 0x42;
    comp_len = sizeof(comp);
    status = mz_compress(comp, &comp_len, &one_byte, 1);
    check(status == MZ_OK, "compress_one_byte");
    decomp_len = sizeof(decomp);
    status = mz_uncompress(decomp, &decomp_len, comp, comp_len);
    check(status == MZ_OK && decomp_len == 1 && decomp[0] == 0x42, "roundtrip_one_byte");

    /* Large data round-trip (64KB) */
    size_t large_len = 65536;
    unsigned char *large = (unsigned char *)malloc(large_len);
    for (size_t i = 0; i < large_len; i++)
        large[i] = (unsigned char)(i ^ (i >> 8));

    mz_ulong large_comp_len = mz_compressBound(large_len);
    unsigned char *large_comp = (unsigned char *)malloc(large_comp_len);
    status = mz_compress(large_comp, &large_comp_len, large, large_len);
    check(status == MZ_OK, "compress_large");
    printf("# large: %lu -> %lu bytes\n", (unsigned long)large_len, (unsigned long)large_comp_len);

    mz_ulong large_decomp_len = large_len;
    unsigned char *large_decomp = (unsigned char *)malloc(large_decomp_len);
    status = mz_uncompress(large_decomp, &large_decomp_len, large_comp, large_comp_len);
    check(status == MZ_OK && large_decomp_len == large_len, "uncompress_large");
    check(memcmp(large_decomp, large, large_len) == 0, "large_roundtrip_match");

    /* Verify CRC matches after round-trip */
    mz_ulong orig_crc = mz_crc32(MZ_CRC32_INIT, large, large_len);
    mz_ulong decomp_crc = mz_crc32(MZ_CRC32_INIT, large_decomp, large_decomp_len);
    check(orig_crc == decomp_crc, "large_crc_match");
    printf("# large_crc=%lu\n", orig_crc);

    free(large);
    free(large_comp);
    free(large_decomp);
}

/* --- Deflate reset test --- */
static void test_deflate_reset(void) {
    printf("# Deflate reset\n");

    const char *src = "Test data for deflate reset verification";
    size_t src_len = strlen(src);

    mz_stream stream;
    memset(&stream, 0, sizeof(stream));
    int status = mz_deflateInit(&stream, MZ_DEFAULT_COMPRESSION);
    check(status == MZ_OK, "reset_deflateInit");

    unsigned char comp1[256], comp2[256];

    /* First compression */
    stream.next_in = (const unsigned char *)src;
    stream.avail_in = (unsigned int)src_len;
    stream.next_out = comp1;
    stream.avail_out = sizeof(comp1);
    status = mz_deflate(&stream, MZ_FINISH);
    check(status == MZ_STREAM_END, "reset_first_deflate");
    mz_ulong comp1_len = stream.total_out;

    /* Reset and compress again — should produce same output */
    status = mz_deflateReset(&stream);
    check(status == MZ_OK, "deflateReset");

    stream.next_in = (const unsigned char *)src;
    stream.avail_in = (unsigned int)src_len;
    stream.next_out = comp2;
    stream.avail_out = sizeof(comp2);
    status = mz_deflate(&stream, MZ_FINISH);
    check(status == MZ_STREAM_END, "reset_second_deflate");
    mz_ulong comp2_len = stream.total_out;

    check(comp1_len == comp2_len, "reset_same_size");
    check(memcmp(comp1, comp2, comp1_len) == 0, "reset_same_data");

    mz_deflateEnd(&stream);
}

/* --- tdefl_compress_mem_to_mem test --- */
static void test_mem_to_mem(void) {
    printf("# tdefl_compress_mem_to_mem\n");

    const char *src = "Repetitive data data data data data data data data!";
    size_t src_len = strlen(src);

    unsigned char comp[256];
    int flags = tdefl_create_comp_flags_from_zip_params(MZ_BEST_COMPRESSION, -MZ_DEFAULT_WINDOW_BITS, MZ_DEFAULT_STRATEGY);
    size_t comp_len = tdefl_compress_mem_to_mem(comp, sizeof(comp), src, src_len, flags);
    check(comp_len > 0, "mem_to_mem_compress");
    printf("# mem_to_mem: %lu -> %lu bytes\n", (unsigned long)src_len, (unsigned long)comp_len);

    /* Decompress */
    unsigned char decomp[256];
    size_t decomp_len = tinfl_decompress_mem_to_mem(decomp, sizeof(decomp), comp, comp_len, 0);
    check(decomp_len == src_len, "mem_to_mem_decompress_size");
    check(memcmp(decomp, src, src_len) == 0, "mem_to_mem_decompress_match");
}

int main(void) {
    printf("# miniz core test suite\n");

    test_checksums();
    test_oneshot_roundtrip();
    test_compression_levels();
    test_streaming();
    test_lowlevel();
    test_edge_cases();
    test_deflate_reset();
    test_mem_to_mem();

    printf("1..%d\n", test_count);
    if (fail_count > 0) {
        printf("# %d tests FAILED\n", fail_count);
        return 1;
    }
    printf("# all %d tests passed\n", test_count);
    return 0;
}
