fn main() {
    // Cargo rerun triggers — add every .c and .h we depend on.
    println!("cargo:rerun-if-changed=lapi.c");
    println!("cargo:rerun-if-changed=lauxlib.c");
    println!("cargo:rerun-if-changed=lbaselib.c");
    println!("cargo:rerun-if-changed=lcode.c");
    println!("cargo:rerun-if-changed=lcorolib.c");
    println!("cargo:rerun-if-changed=lctype.c");
    println!("cargo:rerun-if-changed=ldblib.c");
    println!("cargo:rerun-if-changed=ldebug.c");
    println!("cargo:rerun-if-changed=ldo.c");
    println!("cargo:rerun-if-changed=ldump.c");
    println!("cargo:rerun-if-changed=lfunc.c");
    println!("cargo:rerun-if-changed=lgc.c");
    println!("cargo:rerun-if-changed=linit.c");
    println!("cargo:rerun-if-changed=liolib.c");
    println!("cargo:rerun-if-changed=llex.c");
    println!("cargo:rerun-if-changed=lmathlib.c");
    println!("cargo:rerun-if-changed=lmem.c");
    println!("cargo:rerun-if-changed=loadlib.c");
    println!("cargo:rerun-if-changed=lobject.c");
    println!("cargo:rerun-if-changed=lopcodes.c");
    println!("cargo:rerun-if-changed=loslib.c");
    println!("cargo:rerun-if-changed=lparser.c");
    println!("cargo:rerun-if-changed=lstate.c");
    println!("cargo:rerun-if-changed=lstring.c");
    println!("cargo:rerun-if-changed=lstrlib.c");
    println!("cargo:rerun-if-changed=ltable.c");
    println!("cargo:rerun-if-changed=ltablib.c");
    println!("cargo:rerun-if-changed=ltests.c");
    println!("cargo:rerun-if-changed=ltm.c");
    println!("cargo:rerun-if-changed=lua.c");
    println!("cargo:rerun-if-changed=lundump.c");
    println!("cargo:rerun-if-changed=lutf8lib.c");
    println!("cargo:rerun-if-changed=lvm.c");
    println!("cargo:rerun-if-changed=lzio.c");
    println!("cargo:rerun-if-changed=onelua.c");
    println!("cargo:rerun-if-changed=lapi.h");
    println!("cargo:rerun-if-changed=lauxlib.h");
    println!("cargo:rerun-if-changed=lcode.h");
    println!("cargo:rerun-if-changed=lctype.h");
    println!("cargo:rerun-if-changed=ldebug.h");
    println!("cargo:rerun-if-changed=ldo.h");
    println!("cargo:rerun-if-changed=lfunc.h");
    println!("cargo:rerun-if-changed=lgc.h");
    println!("cargo:rerun-if-changed=ljumptab.h");
    println!("cargo:rerun-if-changed=llex.h");
    println!("cargo:rerun-if-changed=llimits.h");
    println!("cargo:rerun-if-changed=lmem.h");
    println!("cargo:rerun-if-changed=lobject.h");
    println!("cargo:rerun-if-changed=lopcodes.h");
    println!("cargo:rerun-if-changed=lopnames.h");
    println!("cargo:rerun-if-changed=lparser.h");
    println!("cargo:rerun-if-changed=lprefix.h");
    println!("cargo:rerun-if-changed=lstate.h");
    println!("cargo:rerun-if-changed=lstring.h");
    println!("cargo:rerun-if-changed=ltable.h");
    println!("cargo:rerun-if-changed=ltests.h");
    println!("cargo:rerun-if-changed=ltm.h");
    println!("cargo:rerun-if-changed=luaconf.h");
    println!("cargo:rerun-if-changed=lua.h");
    println!("cargo:rerun-if-changed=lualib.h");
    println!("cargo:rerun-if-changed=lundump.h");
    println!("cargo:rerun-if-changed=lvm.h");
    println!("cargo:rerun-if-changed=lzio.h");
    println!("cargo:rerun-if-changed=wrapper.c");
    println!("cargo:rerun-if-changed=wrapper.h");

    cc::Build::new()
        .file("lapi.c")
        .file("lauxlib.c")
        .file("lbaselib.c")
        .file("lcode.c")
        .file("lcorolib.c")
        .file("lctype.c")
        .file("ldblib.c")
        .file("ldebug.c")
        .file("ldo.c")
        .file("ldump.c")
        .file("lfunc.c")
        .file("lgc.c")
        .file("linit.c")
        .file("liolib.c")
        .file("llex.c")
        .file("lmathlib.c")
        .file("lmem.c")
        .file("loadlib.c")
        .file("lobject.c")
        .file("lopcodes.c")
        .file("loslib.c")
        .file("lparser.c")
        .file("lstate.c")
        .file("lstring.c")
        .file("lstrlib.c")
        .file("ltable.c")
        .file("ltablib.c")
        .file("ltests.c")
        .file("ltm.c")
        .file("lua.c")
        .file("lundump.c")
        .file("lutf8lib.c")
        .file("lvm.c")
        .file("lzio.c")
        .file("onelua.c")
        .file("wrapper.c")
        .include(".")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-function")
        .compile("lua_wrapper");
}
